<?php

namespace App\Common\Constants\ServicePackage\Meta;

enum MetaVertical: string
{
    case ADVERTISING = 'ADVERTISING';
    case AUTOMOTIVE = 'AUTOMOTIVE';
    case CONSUMER_PACKAGED_GOODS = 'CONSUMER_PACKAGED_GOODS';
    case ECOMMERCE = 'ECOMMERCE';
    case EDUCATION = 'EDUCATION';
    case ENERGY_AND_UTILITIES = 'ENERGY_AND_UTILITIES';
    case ENTERTAINMENT_AND_MEDIA = 'ENTERTAINMENT_AND_MEDIA';
    case FINANCIAL_SERVICES = 'FINANCIAL_SERVICES';
    case GAMING = 'GAMING';
    case GOVERNMENT_AND_POLITICS = 'GOVERNMENT_AND_POLITICS';
    case MARKETING = 'MARKETING';
    case ORGANIZATIONS_AND_ASSOCIATIONS = 'ORGANIZATIONS_AND_ASSOCIATIONS';
    case PROFESSIONAL_SERVICES = 'PROFESSIONAL_SERVICES';
    case RETAIL = 'RETAIL';
    case TECHNOLOGY = 'TECHNOLOGY';
    case TELECOM = 'TELECOM';
    case TRAVEL = 'TRAVEL';
    case OTHER = 'OTHER';
}
