<?php

namespace App\Common\Constants\Config;

enum ConfigName: string
{
    case CRYPTO_DEPOSIT_METHOD = 'CRYPTO_DEPOSIT_METHOD';
    case BEP20_WALLET_ADDRESS = 'BEP20_WALLET_ADDRESS';
    case TRC20_WALLET_ADDRESS = 'TRC20_WALLET_ADDRESS';
    case POSTPAY_MIN_BALANCE = 'POSTPAY_MIN_BALANCE';
    case THRESHOLD_PAUSE = 'THRESHOLD_PAUSE'; // ngưỡng tạm dừng khi balance thấp
    case COINREMITTER_TRC20_API_KEY = 'COINREMITTER_TRC20_API_KEY';
    case COINREMITTER_TRC20_PASSWORD = 'COINREMITTER_TRC20_PASSWORD';
    case COINREMITTER_BEP20_API_KEY = 'COINREMITTER_BEP20_API_KEY';
    case COINREMITTER_BEP20_PASSWORD = 'COINREMITTER_BEP20_PASSWORD';
}
